import subprocess
import tempfile
from pathlib import Path
from typing import Optional

NOTES_TO_PRD_PROMPT = Path(__file__).parent.parent / "prompts" / "notes_to_prd.md"
PRD_TO_STORIES_PROMPT = Path(__file__).parent.parent / "prompts" / "prd_to_stories.md"


def call_claude(prompt: str, model: str = "sonnet") -> str:
    """Call claude --print with a prompt string. Returns stdout."""
    with tempfile.NamedTemporaryFile(mode="w", suffix=".md", delete=False) as f:
        f.write(prompt)
        prompt_file = f.name

    with open(prompt_file) as stdin_f:
        result = subprocess.run(
            ["claude", "--print", "--model", model, "--dangerously-skip-permissions"],
            stdin=stdin_f,
            capture_output=True,
            text=True,
        )

    if result.returncode != 0:
        raise RuntimeError(f"claude exited {result.returncode}: {result.stderr[:500]}")

    return result.stdout.strip()


def _build_codebase_context(codebase: Optional[Path]) -> str:
    if codebase is None:
        return ""

    context_parts = ["## Existing Codebase\n"]
    py_files = [
        f for f in codebase.rglob("*.py")
        if ".venv" not in str(f) and "__pycache__" not in str(f)
    ]
    for py_file in sorted(py_files)[:20]:
        rel = py_file.relative_to(codebase)
        content = py_file.read_text()[:3000]
        context_parts.append(f"### `{rel}`\n```python\n{content}\n```\n")

    return "\n".join(context_parts)


def run_prd_pipeline(
    notes_path: Path,
    codebase: Optional[Path],
    model: str = "sonnet",
) -> str:
    """Two-stage pipeline: notes → PRD → stories. Returns plan.md content."""
    notes = notes_path.read_text()

    notes_prompt_template = NOTES_TO_PRD_PROMPT.read_text()
    notes_prompt = notes_prompt_template.format(notes=notes)
    prd = call_claude(notes_prompt, model=model)

    stories_prompt_template = PRD_TO_STORIES_PROMPT.read_text()
    codebase_context = _build_codebase_context(codebase)
    stories_prompt = stories_prompt_template.format(
        prd=prd,
        codebase_context=codebase_context,
    )
    stories = call_claude(stories_prompt, model=model)

    header = (
        "# Implementation Plan\n\n"
        "Generated by Raphael. Edit freely — the executor reads this file.\n\n"
        "---\n\n"
    )
    return header + stories
